# Generated by Django 2.2.11 on 2020-05-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0003_auto_20200520_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonFingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.ImageField(upload_to='fingerprints')),
                ('encoding', models.BinaryField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='person.Person')),
            ],
        ),
    ]
