# Generated by Django 2.2.11 on 2020-05-20 16:23

from django.db import migrations, models
import django.db.models.deletion
import iris.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0002_auto_20200520_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=iris.models.handler_upload)),
                ('encoding', models.BinaryField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iris', to='person.Person')),
            ],
        ),
    ]
