# Generated by Django 2.2.11 on 2020-05-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20200520_0720'),
        ('iris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIrisCompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compare_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iris_stat', to='iris.PersonIris')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iris_stat', to='person.Person')),
            ],
            options={
                'ordering': ['percentage'],
            },
        ),
    ]
