# Generated by Django 2.2.11 on 2020-05-20 21:09

from django.db import migrations, models
import iris.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0003_personiris_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personiriscompare',
            name='compare_with',
            field=models.ImageField(upload_to=iris.models.handler_compare_path),
        ),
    ]
