# Generated by Django 2.2.11 on 2020-05-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0004_auto_20200520_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonIrisCompare',
        ),
    ]
