# Generated by Django 2.2.11 on 2020-05-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personimage',
            name='encoding',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
