# Generated by Django 2.2.11 on 2020-05-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_entry', '0002_logentry_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
